
package com.rapid_i.repository.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProcessService", targetNamespace = "http://service.web.rapidrepository.com/", wsdlLocation = "http://localhost:8080/RapidRepositoryWeb/ProcessService?wsdl")
public class ProcessService_Service
    extends Service
{

    private final static URL PROCESSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RapidRepositoryWeb/ProcessService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PROCESSSERVICE_WSDL_LOCATION = url;
    }

    public ProcessService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessService_Service() {
        super(PROCESSSERVICE_WSDL_LOCATION, new QName("http://service.web.rapidrepository.com/", "ProcessService"));
    }

    /**
     * 
     * @return
     *     returns ProcessService
     */
    @WebEndpoint(name = "ProcessServicePort")
    public ProcessService getProcessServicePort() {
        return (ProcessService)super.getPort(new QName("http://service.web.rapidrepository.com/", "ProcessServicePort"), ProcessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessService
     */
    @WebEndpoint(name = "ProcessServicePort")
    public ProcessService getProcessServicePort(WebServiceFeature... features) {
        return (ProcessService)super.getPort(new QName("http://service.web.rapidrepository.com/", "ProcessServicePort"), ProcessService.class, features);
    }

}
