
package com.rapid_i.repository.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RepositoryService", targetNamespace = "http://service.web.rapidrepository.com/", wsdlLocation = "http://localhost:8080/RapidRepositoryWeb/RepositoryService?wsdl")
public class RepositoryService_Service
    extends Service
{

    private final static URL REPOSITORYSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RapidRepositoryWeb/RepositoryService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        REPOSITORYSERVICE_WSDL_LOCATION = url;
    }

    public RepositoryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RepositoryService_Service() {
        super(REPOSITORYSERVICE_WSDL_LOCATION, new QName("http://service.web.rapidrepository.com/", "RepositoryService"));
    }

    /**
     * 
     * @return
     *     returns RepositoryService
     */
    @WebEndpoint(name = "RepositoryServicePort")
    public RepositoryService getRepositoryServicePort() {
        return (RepositoryService)super.getPort(new QName("http://service.web.rapidrepository.com/", "RepositoryServicePort"), RepositoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RepositoryService
     */
    @WebEndpoint(name = "RepositoryServicePort")
    public RepositoryService getRepositoryServicePort(WebServiceFeature... features) {
        return (RepositoryService)super.getPort(new QName("http://service.web.rapidrepository.com/", "RepositoryServicePort"), RepositoryService.class, features);
    }

}
